baseURL = 'https://regularrecipes.com/'
title = 'Regular Recipes'
languageCode = 'en-us'

[params]
  description = "A site with regular recipes"
  dark = "auto"
  highlight = true

[menu]
  [[menu.main]]
    identifier = "recipes"
    name = "recipes"
    title = "recipes"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "about"
    url = "/about/"
    weight = 20

[permalinks]
  recipes = "/:title/"
